<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xrohzKf' shared service.

return $this->privates['.service_locator.xrohzKf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenaire' => ['privates', '.errored..service_locator.xrohzKf.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.xrohzKf": it references class "App\\Entity\\Partenaire" but no such service exists.'],
], [
    'partenaire' => 'App\\Entity\\Partenaire',
]);
