<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fO7IJMX' shared service.

return $this->privates['.service_locator.fO7IJMX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::delete' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController::edit' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController::index' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\PartenaireController::show' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PartenaireController:delete' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController:edit' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController:index' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\PartenaireController:show' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\PartenaireController::delete' => '?',
    'App\\Controller\\PartenaireController::edit' => '?',
    'App\\Controller\\PartenaireController::index' => '?',
    'App\\Controller\\PartenaireController::show' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\PartenaireController:delete' => '?',
    'App\\Controller\\PartenaireController:edit' => '?',
    'App\\Controller\\PartenaireController:index' => '?',
    'App\\Controller\\PartenaireController:show' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
