<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3iPZAwk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3iPZAwk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3iPZAwk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3iPZAwk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3iPZAwk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3iPZAwk',
    'container.build_id' => '9abaa1cd',
    'container.build_time' => 1564483462,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3iPZAwk');
