<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfGWB1E\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfGWB1E/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfGWB1E.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfGWB1E\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXfGWB1E\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XfGWB1E',
    'container.build_id' => '7f188065',
    'container.build_time' => 1564360032,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfGWB1E');
