<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSmj9OVD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSmj9OVD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSmj9OVD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSmj9OVD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSmj9OVD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Smj9OVD',
    'container.build_id' => 'ebcdbd04',
    'container.build_time' => 1564480480,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSmj9OVD');
